# Travis CI build file for KituraBuddy.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - jazzy_travis
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"Docs"* ]]; then sudo gem install jazzy && sudo jazzy ; fi

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
